"""Stable FBX-to-Dying-Light animation pipeline surface.

The low-level implementation remains in the reverse-engineering-backed builder,
but callers should use this module.  The GUI/project layer builds on the same
API and adds project persistence plus create/append RPack orchestration.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

ROOT_POLICIES = ("inplace", "bip01", "motion")


@dataclass(frozen=True, slots=True)
class FbxAnimationClip:
    path: str | Path
    stack_name: str = ""


def build_fbx_rpack(
    *,
    animation_fbxs: Sequence[str | Path] | None = None,
    animation_clips: Sequence[FbxAnimationClip] | None = None,
    source_rest_fbx: str | Path,
    trusted_source_rest_json: str | Path | None = None,
    canonical_smd: str | Path,
    target_template_anm2: str | Path,
    stock_writer_control_anm2: str | Path,
    out_dir: str | Path,
    root_policies: Sequence[str] = ("inplace", "motion"),
    ik_authoring_preset: str = "runtime",
    source_bone_aliases: Mapping[str, str] | None = None,
    animation_script_resource_name: str = "anims_man_all_DLC60",
    include_controls: bool = True,
    helper_rules: Sequence[Mapping[str, Any]] | None = None,
    helper_target_profile: str = "dl1_legacy_70_track",
    source_root_bone: str = "mixamorig:Hips",
    target_root_bone: str = "bip01",
    root_heading_modes: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Build custom ANM2 resources and one editor-loadable RPack.

    ``source_rest_fbx`` may be the animation FBX itself. In project schema 2,
    embedded-bind mode does exactly that and reads the clip's unanimated transforms,
    avoiding a separate T-pose file when the FBX contains reliable bind data.

    ``source_bone_aliases`` maps the canonical semantic names consumed by the
    retargeter (for example ``mixamorig:LeftArm``) to the actual names in the
    imported FBX.  It is normally generated by a ``.dlrmap.json`` profile.

    ``animation_script_resource_name`` is the `_ANIMATION_SCR_` resource to
    create or override.  It is no longer hardcoded to the male NPC test script.
    """

    # Imported lazily so opening the GUI does not load the research/oracle
    # dependency graph. The full retarget pipeline is loaded only when a build
    # is requested.
    from dlanm2_gui.oracle.custom_fbx_release_candidate_editor_rpack import (
        build_custom_fbx_release_candidate_editor_rpack,
    )

    return build_custom_fbx_release_candidate_editor_rpack(
        animation_fbxs=animation_fbxs,
        animation_clips=animation_clips,
        source_rest_fbx=source_rest_fbx,
        trusted_source_rest_json=trusted_source_rest_json,
        canonical_smd=canonical_smd,
        target_template_anm2=target_template_anm2,
        stock_writer_control_anm2=stock_writer_control_anm2,
        out_dir=out_dir,
        root_policies=root_policies,
        ik_authoring_preset=ik_authoring_preset,
        source_bone_aliases=source_bone_aliases,
        animation_script_resource_name=animation_script_resource_name,
        include_controls=include_controls,
        helper_rules=helper_rules,
        helper_target_profile=helper_target_profile,
        source_root_bone=source_root_bone,
        target_root_bone=target_root_bone,
        root_heading_modes=root_heading_modes,
    )


__all__ = ["FbxAnimationClip", "ROOT_POLICIES", "build_fbx_rpack"]
