<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>ReAnimated.Renderer.D3D11</RootNamespace>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ReAnimated.Core\ReAnimated.Core.csproj" />
    <ProjectReference Include="..\ReAnimated.Evaluation\ReAnimated.Evaluation.csproj" />
    <PackageReference Include="Vortice.D3DCompiler" />
    <PackageReference Include="Vortice.Direct3D11" />
    <PackageReference Include="Vortice.DXGI" />
  </ItemGroup>
</Project>
