using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Nodes;
using ReAnimated.Codecs.Anm2;
using ReAnimated.Codecs.Fbx;
using ReAnimated.Codecs.Models;
using ReAnimated.Core.Domain;
using ReAnimated.Core.Mathematics;
using ReAnimated.Core.ModelAuthoring;
using ReAnimated.Core.Project;

namespace ReAnimated.Tests;

public sealed class Dl1DeveloperToolsDeploymentTests
{
    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public void CharacterModelAndAnimationLibraryIdentitiesRemainIndependent()
    {
        CustomModelDocument document = CreateDocument(
            new CustomModelBuildSettings
            {
                CharacterId = "generic_character",
                ResourceName = "GenericModel",
                SurfaceName = "default",
                AnimationScriptAlias = "GenericAnimationLibrary",
            });

        document.Validate();

        Assert.Equal("generic_character", document.BuildSettings.CharacterId);
        Assert.Equal("GenericModel", document.BuildSettings.ResourceName);
        Assert.Equal("GenericAnimationLibrary", document.BuildSettings.AnimationScriptAlias);
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public void LegacySchemaOneSettingsMayOmitCharacterId()
    {
        CustomModelDocument document = CreateDocument(
            new CustomModelBuildSettings
            {
                ResourceName = "generic_model",
                SurfaceName = "default",
            });

        document.Validate();

        Assert.Equal(string.Empty, document.BuildSettings.CharacterId);
    }

    [Theory]
    [InlineData(".")]
    [InlineData("..")]
    [InlineData("characters/other")]
    [InlineData("characters\\other")]
    [InlineData("C:\\absolute")]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public void CharacterIdRejectsTraversalAndPathSyntax(string characterId)
    {
        CustomModelDocument document = CreateDocument(
            new CustomModelBuildSettings
            {
                CharacterId = characterId,
                ResourceName = "generic_model",
                SurfaceName = "default",
            });

        ArgumentException error = Assert.Throws<ArgumentException>(document.Validate);

        Assert.Contains("one safe directory component", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public void LooseAnimationScriptUsesCanonicalDeterministicSeqTracks()
    {
        string script = CustomModelAnimationLibraryExporter.BuildLooseAnimationScript(
        [
            new AnimationScrSequence("walk", "walk.anm2", 0, 47, 24, 1, 0.5f),
            new AnimationScrSequence("idle", "idle.anm2", 0, 89, 30, 1, 0.5f),
        ]);

        Assert.Equal(
            "// Generated by DL ReAnimated. Source timing matches compiled ANM2 output.\n" +
            "SeqTrack( \"idle\", \"idle.anm2\", 0, 89, 30, 1, 0.5 )\n" +
            "SeqTrack( \"walk\", \"walk.anm2\", 0, 47, 24, 1, 0.5 )\n",
            script);
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task PreflightUsesCanonicalProjectPathsWithoutNestedPackageLayout()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest request = CreateDeploymentRequest(
                directory,
                installLooseAnm2: true,
                exportPortableAnimationRpack: true);

            Dl1DeveloperToolsDeploymentPlan plan =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(request);

            Assert.True(plan.CanDeploy);
            Assert.Equal("generic_character", plan.CharacterId);
            Assert.Equal("GenericModel", plan.ModelResourceName);
            Assert.Equal("GenericLibrary", plan.AnimationLibraryName);
            Assert.Equal(
                "data/characters/animations/animscripts/GenericLibrary.scr",
                plan.AnimationScriptRelativePath);
            Assert.Equal(["idle_loop"], plan.AnimationNames.ToArray());
            Dl1DeveloperToolsDeploymentAnimation animation = Assert.Single(plan.Animations);
            Assert.Equal("Idle Take", animation.SourceName);
            Assert.Equal("idle_loop", animation.AnimationName);
            Assert.Equal("idle_loop.anm2", animation.Anm2FileName);
            Assert.Equal(0, animation.StartFrame);
            Assert.Equal(2, animation.EndFrame);
            Assert.Equal(30, animation.FramesPerSecond);
            Assert.Equal(
                "SeqTrack( \"idle_loop\", \"idle_loop.anm2\", 0, 2, 30, 1, 0.5 )",
                animation.ScrSequence);
            Assert.Equal(
                "out/ReAnimated/GenericModel/GenericLibrary_pc.rpack",
                plan.PortableRpackRelativePath);

            Dictionary<string, Dl1DeveloperToolsDeploymentArtifact> artifacts = plan.Artifacts
                .ToDictionary(static artifact => artifact.RelativePath, StringComparer.OrdinalIgnoreCase);
            AssertArtifact(
                artifacts,
                "data/characters/generic_character/GenericModel.msh",
                Dl1DeploymentArtifactRole.Source);
            AssertArtifact(
                artifacts,
                "data/characters/generic_character/GenericModel.chr",
                Dl1DeploymentArtifactRole.Source);
            AssertArtifact(
                artifacts,
                "data/characters/generic_character/GenericModel.bscr",
                Dl1DeploymentArtifactRole.Source);
            AssertArtifact(
                artifacts,
                "data/characters/generic_character/GenericModel.ascr",
                Dl1DeploymentArtifactRole.Source);
            AssertArtifact(
                artifacts,
                "data/characters/animations/animscripts/GenericLibrary.scr",
                Dl1DeploymentArtifactRole.Source);
            AssertArtifact(
                artifacts,
                "data/characters/animations/idle_loop.anm2",
                Dl1DeploymentArtifactRole.Source);
            AssertArtifact(
                artifacts,
                "assets_pc/characters/generic_character/GenericModel.msh_obj",
                Dl1DeploymentArtifactRole.Compiled);
            AssertArtifact(
                artifacts,
                "assets_pc/characters/animations/idle_loop.anm2_obj",
                Dl1DeploymentArtifactRole.Compiled);
            AssertArtifact(
                artifacts,
                "assets_pc/local_dx11.mp",
                Dl1DeploymentArtifactRole.Shared);
            AssertArtifact(
                artifacts,
                "out/ReAnimated/GenericModel/GenericLibrary_pc.rpack",
                Dl1DeploymentArtifactRole.PortableOnly);
            AssertArtifact(
                artifacts,
                ".dl-reanimated/deployments/<deployment-id>.json",
                Dl1DeploymentArtifactRole.ManifestOwned);

            Assert.DoesNotContain(
                artifacts.Keys,
                static path =>
                    path.StartsWith("compiled/", StringComparison.OrdinalIgnoreCase) ||
                    path.StartsWith("loose/", StringComparison.OrdinalIgnoreCase) ||
                    path.Contains("/compiled/", StringComparison.OrdinalIgnoreCase) ||
                    path.Contains("/loose/", StringComparison.OrdinalIgnoreCase));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task LegacyNestedOutputRequiresExplicitRecoverableBackup()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest request = CreateDeploymentRequest(
                directory,
                installLooseAnm2: false,
                exportPortableAnimationRpack: false);
            string legacyFile = Path.Combine(
                request.ProjectRoot,
                "compiled",
                "loose",
                "animations",
                "old.bin");
            Directory.CreateDirectory(Path.GetDirectoryName(legacyFile)!);
            await File.WriteAllTextAsync(legacyFile, "legacy payload");

            Dl1DeveloperToolsDeploymentPlan plan =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(
                    request);

            Assert.Equal(["compiled"], plan.LegacyOutputPaths.ToArray());
            Assert.Single(plan.LegacyOutputWarnings);
            Assert.True(File.Exists(legacyFile));

            Dl1DeveloperToolsLegacyBackupResult backup =
                await Dl1DeveloperToolsProjectDeployer.BackUpLegacyOutputsAsync(request.ProjectRoot);

            Assert.Equal(["compiled"], backup.BackedUpRelativePaths.ToArray());
            Assert.False(Directory.Exists(Path.Combine(request.ProjectRoot, "compiled")));
            string backedUp = Path.Combine(
                request.ProjectRoot,
                backup.BackupRootRelativePath.Replace('/', Path.DirectorySeparatorChar),
                "compiled",
                "loose",
                "animations",
                "old.bin");
            Assert.Equal("legacy payload", await File.ReadAllTextAsync(backedUp));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Theory]
    [InlineData(true, true)]
    [InlineData(true, false)]
    [InlineData(false, true)]
    [InlineData(false, false)]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task PreflightHonorsOptionalLooseAnimationAndPortableRpack(
        bool installLooseAnm2,
        bool exportPortableAnimationRpack)
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentPlan plan =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(
                    CreateDeploymentRequest(
                        directory,
                        installLooseAnm2,
                        exportPortableAnimationRpack));

            Assert.True(plan.CanDeploy);
            Assert.Equal(installLooseAnm2, plan.InstallLooseAnm2);
            Assert.Equal(exportPortableAnimationRpack, plan.ExportPortableAnimationRpack);
            Assert.Equal(
                installLooseAnm2,
                plan.Artifacts.Any(static artifact =>
                    artifact.RelativePath == "data/characters/animations/idle_loop.anm2"));
            Assert.Equal(
                exportPortableAnimationRpack,
                plan.Artifacts.Any(static artifact =>
                    artifact.RelativePath == "out/ReAnimated/GenericModel/GenericLibrary_pc.rpack" &&
                    artifact.Role == Dl1DeploymentArtifactRole.PortableOnly));

            Dl1DeveloperToolsDeploymentArtifact compiledAnimation = Assert.Single(
                plan.Artifacts.Where(static artifact =>
                    artifact.RelativePath == "assets_pc/characters/animations/idle_loop.anm2_obj"));
            Assert.Equal(Dl1DeploymentArtifactRole.Compiled, compiledAnimation.Role);
            Assert.True(compiledAnimation.Required);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task PreflightBlocksUnownedRequiredArtifactUntilExplicitReplacement()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest blockedRequest = CreateDeploymentRequest(
                directory,
                installLooseAnm2: false,
                exportPortableAnimationRpack: false);
            string relativePath = "data/characters/generic_character/GenericModel.ascr";
            string existingPath = Path.Combine(
                blockedRequest.ProjectRoot,
                relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(existingPath)!);
            await File.WriteAllTextAsync(existingPath, "unowned animation redirect");

            Dl1DeveloperToolsDeploymentPlan blocked =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(blockedRequest);

            Assert.False(blocked.CanDeploy);
            Dl1DeveloperToolsDeploymentConflict conflict = Assert.Single(
                blocked.Conflicts.Where(conflict =>
                    string.Equals(conflict.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase)));
            Assert.False(conflict.CanSkip);
            Dl1DeveloperToolsDeploymentArtifact blockedArtifact = Assert.Single(
                blocked.Artifacts.Where(artifact =>
                    string.Equals(artifact.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase)));
            Assert.Equal(Dl1DeploymentArtifactDisposition.Conflict, blockedArtifact.Disposition);
            Assert.False(blockedArtifact.ExistingFileIsOwned);
            Assert.NotNull(blockedArtifact.ExistingSha256);
            Assert.NotNull(blockedArtifact.PreparedSha256);

            Dl1DeveloperToolsDeploymentRequest replaceRequest = blockedRequest with
            {
                ConflictResolutions = ImmutableDictionary<string, Dl1DeploymentConflictResolution>.Empty
                    .WithComparers(StringComparer.OrdinalIgnoreCase)
                    .Add(relativePath.ToUpperInvariant(), Dl1DeploymentConflictResolution.BackUpAndReplace),
            };
            Dl1DeveloperToolsDeploymentPlan replacement =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(replaceRequest);

            Assert.True(replacement.CanDeploy);
            Assert.Empty(replacement.Conflicts);
            Dl1DeveloperToolsDeploymentArtifact replacementArtifact = Assert.Single(
                replacement.Artifacts.Where(artifact =>
                    string.Equals(artifact.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase)));
            Assert.Equal(
                Dl1DeploymentArtifactDisposition.ReplaceUnowned,
                replacementArtifact.Disposition);
            Assert.False(replacementArtifact.ExistingFileIsOwned);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task PreflightAllowsExplicitSkipOnlyForUnownedOptionalArtifact()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest blockedRequest = CreateDeploymentRequest(
                directory,
                installLooseAnm2: true,
                exportPortableAnimationRpack: false);
            string relativePath = "data/characters/animations/idle_loop.anm2";
            string existingPath = Path.Combine(
                blockedRequest.ProjectRoot,
                relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(existingPath)!);
            await File.WriteAllBytesAsync(existingPath, "unowned animation"u8.ToArray());

            Dl1DeveloperToolsDeploymentPlan blocked =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(blockedRequest);

            Assert.False(blocked.CanDeploy);
            Dl1DeveloperToolsDeploymentConflict conflict = Assert.Single(
                blocked.Conflicts.Where(item =>
                    string.Equals(item.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase)));
            Assert.True(conflict.CanSkip);

            Dl1DeveloperToolsDeploymentRequest skipRequest = blockedRequest with
            {
                ConflictResolutions = ImmutableDictionary<string, Dl1DeploymentConflictResolution>.Empty
                    .WithComparers(StringComparer.OrdinalIgnoreCase)
                    .Add(relativePath, Dl1DeploymentConflictResolution.Skip),
            };
            Dl1DeveloperToolsDeploymentPlan skipped =
                await Dl1DeveloperToolsProjectDeployer.PreflightAsync(skipRequest);

            Assert.True(skipped.CanDeploy);
            Dl1DeveloperToolsDeploymentArtifact artifact = Assert.Single(
                skipped.Artifacts.Where(item =>
                    string.Equals(item.RelativePath, relativePath, StringComparison.OrdinalIgnoreCase)));
            Assert.Equal(Dl1DeploymentArtifactDisposition.Skip, artifact.Disposition);
            Assert.False(artifact.Required);
            Assert.False(artifact.ExistingFileIsOwned);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task SuccessfulDeploymentCanRestoreEveryPublishedArtifactFromReceipt()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            const string redirectPath = "data/characters/generic_character/GenericModel.ascr";
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true));
            await WriteProjectFileAsync(request.ProjectRoot, "unrelated/sentinel.txt", "retain me");
            await WriteProjectFileAsync(request.ProjectRoot, redirectPath, "legacy redirect");
            request = ResolveConflict(
                request,
                redirectPath,
                Dl1DeploymentConflictResolution.BackUpAndReplace);

            Dl1DeveloperToolsDeploymentResult deployed =
                await Dl1DeveloperToolsProjectDeployer.DeployAsync(request);

            Assert.True(File.Exists(deployed.ReceiptPath));
            Dl1DeveloperToolsDeploymentReceipt restored = Assert.IsType<Dl1DeveloperToolsDeploymentReceipt>(
                Dl1DeveloperToolsProjectDeployer.LoadLatestActiveReceipt(request.ProjectRoot));
            Assert.Equal(deployed.Receipt.DeploymentId, restored.DeploymentId);
            Assert.Equal(deployed.ReceiptPath, restored.ManifestPath);
            Assert.Equal("GenericLibrary", deployed.Receipt.AnimationLibraryName);
            Assert.Equal(
                "data/characters/animations/animscripts/GenericLibrary.scr",
                deployed.Receipt.AnimationScriptRelativePath);
            Assert.Contains(
                deployed.Receipt.Artifacts,
                static artifact =>
                    artifact.RelativePath == "assets_pc/characters/animations/idle_loop.anm2_obj" &&
                    artifact.Role == Dl1DeploymentArtifactRole.Compiled &&
                    artifact.ChangedByDeployment);
            Assert.Contains(
                deployed.Receipt.Artifacts,
                static artifact =>
                    artifact.RelativePath == "out/ReAnimated/GenericModel/GenericLibrary_pc.rpack" &&
                    artifact.Role == Dl1DeploymentArtifactRole.PortableOnly &&
                    artifact.CreatedByDeployment);
            Assert.Equal(
                "AnimScriptAlias(\"GenericLibrary.scr\")\n",
                await ReadProjectFileAsync(request.ProjectRoot, redirectPath));
            Assert.Contains(
                "SeqTrack( \"idle_loop\", \"idle_loop.anm2\", 0, 2, 30, 1, 0.5 )",
                await ReadProjectFileAsync(
                    request.ProjectRoot,
                    "data/characters/animations/animscripts/GenericLibrary.scr"),
                StringComparison.Ordinal);

            await Dl1DeveloperToolsProjectDeployer.RollbackAsync(deployed.ReceiptPath);

            Assert.Null(Dl1DeveloperToolsProjectDeployer.LoadLatestActiveReceipt(request.ProjectRoot));

            Assert.Equal("legacy redirect", await ReadProjectFileAsync(request.ProjectRoot, redirectPath));
            Assert.Equal(
                "retain me",
                await ReadProjectFileAsync(request.ProjectRoot, "unrelated/sentinel.txt"));
            Assert.False(ProjectFileExists(
                request.ProjectRoot,
                "data/characters/animations/idle_loop.anm2"));
            Assert.False(ProjectFileExists(
                request.ProjectRoot,
                "assets_pc/characters/animations/idle_loop.anm2_obj"));
            Assert.False(ProjectFileExists(
                request.ProjectRoot,
                "out/ReAnimated/GenericModel/GenericLibrary_pc.rpack"));

            using JsonDocument receipt = JsonDocument.Parse(await File.ReadAllTextAsync(deployed.ReceiptPath));
            Assert.NotEqual(
                JsonValueKind.Null,
                receipt.RootElement.GetProperty("rolledBackUtc").ValueKind);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task CompilerFailureRetainsExactPriorProject()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true)) with
            {
                ModelCompilerOverride = static (_, _) =>
                    throw new InvalidOperationException("Synthetic compiler failure."),
            };
            await WriteProjectFileAsync(request.ProjectRoot, "existing/state.bin", "original state");
            ImmutableDictionary<string, ImmutableArray<byte>> before =
                await SnapshotProjectAsync(request.ProjectRoot);

            InvalidOperationException error = await Assert.ThrowsAsync<InvalidOperationException>(
                () => Dl1DeveloperToolsProjectDeployer.DeployAsync(request));

            Assert.Contains("Synthetic compiler failure", error.Message, StringComparison.Ordinal);
            AssertProjectSnapshotsEqual(before, await SnapshotProjectAsync(request.ProjectRoot));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task CompilerCancellationRetainsExactPriorProject()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            using var cancellation = new CancellationTokenSource();
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true)) with
            {
                ModelCompilerOverride = (_, token) =>
                {
                    cancellation.Cancel();
                    return Task.FromCanceled<Dl1OfficialModelCompilerResult>(token);
                },
            };
            await WriteProjectFileAsync(request.ProjectRoot, "existing/state.bin", "original state");
            ImmutableDictionary<string, ImmutableArray<byte>> before =
                await SnapshotProjectAsync(request.ProjectRoot);

            await Assert.ThrowsAnyAsync<OperationCanceledException>(
                () => Dl1DeveloperToolsProjectDeployer.DeployAsync(request, cancellation.Token));

            AssertProjectSnapshotsEqual(before, await SnapshotProjectAsync(request.ProjectRoot));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task MidCommitPublicationFailureRestoresExactPriorProject()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            const string redirectPath = "data/characters/generic_character/GenericModel.ascr";
            int publishedCount = 0;
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true)) with
            {
                ArtifactPublishedObserver = (_, token) =>
                {
                    token.ThrowIfCancellationRequested();
                    if (Interlocked.Increment(ref publishedCount) == 3)
                    {
                        throw new IOException("Synthetic mid-commit publication failure.");
                    }

                    return Task.CompletedTask;
                },
            };
            await WriteProjectFileAsync(request.ProjectRoot, "existing/state.bin", "original state");
            await WriteProjectFileAsync(request.ProjectRoot, redirectPath, "legacy redirect");
            request = ResolveConflict(
                request,
                redirectPath,
                Dl1DeploymentConflictResolution.BackUpAndReplace);
            ImmutableDictionary<string, ImmutableArray<byte>> before =
                await SnapshotProjectAsync(request.ProjectRoot);

            IOException error = await Assert.ThrowsAsync<IOException>(
                () => Dl1DeveloperToolsProjectDeployer.DeployAsync(request));

            Assert.Equal(3, publishedCount);
            Assert.Contains("mid-commit", error.Message, StringComparison.Ordinal);
            AssertProjectSnapshotsEqual(before, await SnapshotProjectAsync(request.ProjectRoot));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task DestinationDriftAfterPreflightIsRejectedWithoutOverwritingExternalChange()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            const string driftPath = "data/characters/generic_character/GenericModel.msh";
            int publishedCount = 0;
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true));
            await WriteProjectFileAsync(request.ProjectRoot, "existing/state.bin", "original state");
            await WriteProjectFileAsync(request.ProjectRoot, driftPath, "preflight state");
            request = ResolveConflict(
                request,
                driftPath,
                Dl1DeploymentConflictResolution.BackUpAndReplace);
            request = request with
            {
                ArtifactPublishedObserver = async (_, token) =>
                {
                    if (Interlocked.Increment(ref publishedCount) != 1)
                    {
                        return;
                    }

                    string destination = ResolveProjectFile(request.ProjectRoot, driftPath);
                    await File.WriteAllTextAsync(destination, "external drift", token);
                },
            };

            Exception error = await Assert.ThrowsAnyAsync<Exception>(
                () => Dl1DeveloperToolsProjectDeployer.DeployAsync(request));

            Assert.True(error is InvalidOperationException or IOException, error.ToString());
            Assert.Contains("changed", error.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Equal("external drift", await ReadProjectFileAsync(request.ProjectRoot, driftPath));
            Assert.Equal(
                "original state",
                await ReadProjectFileAsync(request.ProjectRoot, "existing/state.bin"));
            Assert.False(ProjectFileExists(
                request.ProjectRoot,
                "assets_pc/characters/animations/idle_loop.anm2_obj"));
            Assert.False(ProjectFileExists(
                request.ProjectRoot,
                "assets_pc/characters/generic_character/GenericModel.msh_obj"));
            Assert.Empty(Directory.Exists(Path.Combine(request.ProjectRoot, ".dl-reanimated", "deployments"))
                ? Directory.EnumerateFiles(
                    Path.Combine(request.ProjectRoot, ".dl-reanimated", "deployments"),
                    "*.json",
                    SearchOption.TopDirectoryOnly)
                : []);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task RollbackRejectsTamperedBackupBeforeChangingDeployedFiles()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            const string redirectPath = "data/characters/generic_character/GenericModel.ascr";
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true));
            await WriteProjectFileAsync(request.ProjectRoot, redirectPath, "legacy redirect");
            request = ResolveConflict(
                request,
                redirectPath,
                Dl1DeploymentConflictResolution.BackUpAndReplace);
            Dl1DeveloperToolsDeploymentResult deployed =
                await Dl1DeveloperToolsProjectDeployer.DeployAsync(request);
            Dl1DeveloperToolsDeploymentReceiptArtifact replaced = Assert.Single(
                deployed.Receipt.Artifacts.Where(artifact =>
                    string.Equals(artifact.RelativePath, redirectPath, StringComparison.OrdinalIgnoreCase)));
            Assert.NotNull(replaced.BackupRelativePath);
            await WriteProjectFileAsync(
                request.ProjectRoot,
                replaced.BackupRelativePath!,
                "tampered backup");
            ImmutableDictionary<string, ImmutableArray<byte>> beforeRollback =
                await SnapshotProjectAsync(request.ProjectRoot);

            Exception error = await Assert.ThrowsAnyAsync<Exception>(
                () => Dl1DeveloperToolsProjectDeployer.RollbackAsync(deployed.ReceiptPath));

            Assert.True(error is InvalidDataException or InvalidOperationException, error.ToString());
            Assert.Contains("backup", error.Message, StringComparison.OrdinalIgnoreCase);
            AssertProjectSnapshotsEqual(
                beforeRollback,
                await SnapshotProjectAsync(request.ProjectRoot));
            using JsonDocument receipt = JsonDocument.Parse(await File.ReadAllTextAsync(deployed.ReceiptPath));
            Assert.Equal(
                JsonValueKind.Null,
                receipt.RootElement.GetProperty("rolledBackUtc").ValueKind);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task OlderRollbackIsBlockedWhenNewerActiveDeploymentReferencesUnchangedArtifacts()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true));
            Dl1DeveloperToolsDeploymentResult older =
                await Dl1DeveloperToolsProjectDeployer.DeployAsync(request);
            await Task.Delay(20);
            Dl1DeveloperToolsDeploymentResult newer =
                await Dl1DeveloperToolsProjectDeployer.DeployAsync(request);

            Assert.NotEqual(older.Receipt.DeploymentId, newer.Receipt.DeploymentId);
            Assert.Contains(
                newer.Receipt.Artifacts,
                static artifact => !artifact.ChangedByDeployment);
            ImmutableDictionary<string, ImmutableArray<byte>> beforeRollback =
                await SnapshotProjectAsync(request.ProjectRoot);

            InvalidOperationException error = await Assert.ThrowsAsync<InvalidOperationException>(
                () => Dl1DeveloperToolsProjectDeployer.RollbackAsync(older.ReceiptPath));

            Assert.Contains("newer deployment", error.Message, StringComparison.OrdinalIgnoreCase);
            AssertProjectSnapshotsEqual(
                beforeRollback,
                await SnapshotProjectAsync(request.ProjectRoot));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task RollbackRejectsReceiptWhoseDeploymentIdDoesNotMatchItsFileName()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true));
            Dl1DeveloperToolsDeploymentResult deployed =
                await Dl1DeveloperToolsProjectDeployer.DeployAsync(request);
            JsonObject receipt = JsonNode.Parse(await File.ReadAllTextAsync(deployed.ReceiptPath))!.AsObject();
            receipt["deploymentId"] = new string('f', 24);
            await File.WriteAllTextAsync(
                deployed.ReceiptPath,
                receipt.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
            ImmutableDictionary<string, ImmutableArray<byte>> beforeRollback =
                await SnapshotProjectAsync(request.ProjectRoot);

            InvalidDataException error = await Assert.ThrowsAsync<InvalidDataException>(
                () => Dl1DeveloperToolsProjectDeployer.RollbackAsync(deployed.ReceiptPath));

            Assert.Contains("deployment", error.Message, StringComparison.OrdinalIgnoreCase);
            AssertProjectSnapshotsEqual(
                beforeRollback,
                await SnapshotProjectAsync(request.ProjectRoot));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Fact]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task RollbackRejectsBackupMetadataOutsideItsDeploymentBackupDirectory()
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            const string redirectPath = "data/characters/generic_character/GenericModel.ascr";
            const string unrelatedPath = "unrelated/sentinel.txt";
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true));
            await WriteProjectFileAsync(request.ProjectRoot, redirectPath, "legacy redirect");
            await WriteProjectFileAsync(request.ProjectRoot, unrelatedPath, "unrelated payload");
            request = ResolveConflict(
                request,
                redirectPath,
                Dl1DeploymentConflictResolution.BackUpAndReplace);
            Dl1DeveloperToolsDeploymentResult deployed =
                await Dl1DeveloperToolsProjectDeployer.DeployAsync(request);

            JsonObject receipt = JsonNode.Parse(await File.ReadAllTextAsync(deployed.ReceiptPath))!.AsObject();
            JsonObject artifact = receipt["artifacts"]!.AsArray()
                .Select(static node => node!.AsObject())
                .Single(node => string.Equals(
                    node["relativePath"]!.GetValue<string>(),
                    redirectPath,
                    StringComparison.OrdinalIgnoreCase));
            string unrelatedFile = ResolveProjectFile(request.ProjectRoot, unrelatedPath);
            artifact["backupRelativePath"] = unrelatedPath;
            artifact["previousSha256"] = Convert.ToHexStringLower(
                SHA256.HashData(await File.ReadAllBytesAsync(unrelatedFile)));
            await File.WriteAllTextAsync(
                deployed.ReceiptPath,
                receipt.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
            ImmutableDictionary<string, ImmutableArray<byte>> beforeRollback =
                await SnapshotProjectAsync(request.ProjectRoot);

            InvalidDataException error = await Assert.ThrowsAsync<InvalidDataException>(
                () => Dl1DeveloperToolsProjectDeployer.RollbackAsync(deployed.ReceiptPath));

            Assert.Contains("backup", error.Message, StringComparison.OrdinalIgnoreCase);
            AssertProjectSnapshotsEqual(
                beforeRollback,
                await SnapshotProjectAsync(request.ProjectRoot));
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    [Trait("ValidationTier", "Hermetic")]
    [Trait("Gate", "CustomModelDeployment")]
    public async Task DeploymentRejectsExpectedAscrAliasInCommentOrSecondaryDirective(
        bool useSecondaryDirective)
    {
        string directory = RpackTestData.CreateTemporaryDirectory();
        try
        {
            Dl1DeveloperToolsDeploymentRequest request = WithSyntheticDeploymentPipeline(
                CreateDeploymentRequest(
                    directory,
                    installLooseAnm2: true,
                    exportPortableAnimationRpack: true)) with
            {
                SourceWriterOverride = async (sourceRequest, cancellationToken) =>
                {
                    Dl1SourceModelBuildResult result = await WriteSyntheticSourceAsync(
                        sourceRequest,
                        cancellationToken);
                    string expected = $"AnimScriptAlias(\"{sourceRequest.AnimationScriptAlias}.scr\")";
                    string misleading = useSecondaryDirective ? expected : $"// {expected}";
                    await File.WriteAllTextAsync(
                        result.AnimationScriptPath!,
                        $"AnimScriptAlias(\"WrongLibrary.scr\")\n{misleading}\n",
                        cancellationToken);
                    return result;
                },
            };

            InvalidDataException error = await Assert.ThrowsAsync<InvalidDataException>(
                () => Dl1DeveloperToolsProjectDeployer.DeployAsync(request));

            Assert.Contains("ASCR", error.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Empty(Directory.Exists(Path.Combine(request.ProjectRoot, ".dl-reanimated", "deployments"))
                ? Directory.EnumerateFiles(
                    Path.Combine(request.ProjectRoot, ".dl-reanimated", "deployments"),
                    "*.json",
                    SearchOption.TopDirectoryOnly)
                : []);
        }
        finally
        {
            RpackTestData.DeleteTemporaryDirectory(directory);
        }
    }

    private static void AssertArtifact(
        Dictionary<string, Dl1DeveloperToolsDeploymentArtifact> artifacts,
        string relativePath,
        Dl1DeploymentArtifactRole role)
    {
        Assert.True(artifacts.TryGetValue(relativePath, out Dl1DeveloperToolsDeploymentArtifact? artifact));
        Assert.Equal(role, artifact.Role);
    }

    private static Dl1DeveloperToolsDeploymentRequest CreateDeploymentRequest(
        string directory,
        bool installLooseAnm2,
        bool exportPortableAnimationRpack)
    {
        string projectRoot = Path.Combine(directory, "project");
        string toolsRoot = Path.Combine(directory, "tools");
        Directory.CreateDirectory(projectRoot);
        Directory.CreateDirectory(toolsRoot);
        string compilerPath = Path.Combine(toolsRoot, "compiler.exe");
        string retailDataPath = Path.Combine(toolsRoot, "Data0.pak");
        File.WriteAllBytes(compilerPath, "synthetic compiler marker"u8.ToArray());
        File.WriteAllBytes(retailDataPath, "synthetic retail marker"u8.ToArray());
        return new Dl1DeveloperToolsDeploymentRequest
        {
            Model = CreateSyntheticAnimatedModel(),
            ProjectRoot = projectRoot,
            CompilerExecutablePath = compilerPath,
            RetailData0PakPath = retailDataPath,
            CharacterId = "Generic Character",
            ModelResourceName = "GenericModel",
            SurfaceName = "default",
            AnimationLibraryName = "GenericLibrary",
            InstallLooseAnm2 = installLooseAnm2,
            ExportPortableAnimationRpack = exportPortableAnimationRpack,
        };
    }

    private static Dl1DeveloperToolsDeploymentRequest WithSyntheticDeploymentPipeline(
        Dl1DeveloperToolsDeploymentRequest request) =>
        request with
        {
            SourceWriterOverride = WriteSyntheticSourceAsync,
            ModelCompilerOverride = WriteSyntheticModelCompilerAsync,
            AnimationCompilerOverride = WriteSyntheticAnimationsAsync,
        };

    private static Dl1DeveloperToolsDeploymentRequest ResolveConflict(
        Dl1DeveloperToolsDeploymentRequest request,
        string relativePath,
        Dl1DeploymentConflictResolution resolution) =>
        request with
        {
            ConflictResolutions = request.ConflictResolutions.SetItem(relativePath, resolution),
        };

    private static FbxModelAuthoringImportResult CreateSyntheticAnimatedModel()
    {
        byte[] source = "Kaydara FBX Binary  generic deployment fixture"u8.ToArray();
        string sourceHash = Convert.ToHexString(SHA256.HashData(source)).ToLowerInvariant();
        Guid clipId = new("caedaa1d-4697-5685-a550-2abb1ca2f305");
        var document = new CustomModelDocument
        {
            ModelId = new Guid("e4bfe280-6580-570c-a69d-ce6489188b68"),
            Name = "Generic animated model",
            RigMode = CustomModelRigMode.ExactFbxRig,
            Source = new CustomModelSourceIdentity
            {
                OriginalFileName = "generic.fbx",
                ContentSha256 = sourceHash,
                FbxVersion = 7400,
            },
            RigSignature = sourceHash,
            Bones =
            [
                new CustomModelBone
                {
                    Index = 0,
                    FbxObjectId = 1,
                    Name = "root",
                    ParentIndex = -1,
                    LocalBindTransform = TransformTRS.Identity,
                    ExactLocalBindMatrix = TransformMatrix.Identity,
                    Kind = BoneKind.Root,
                    IsWeighted = true,
                },
            ],
            Meshes = [],
            Materials = [],
            AnimationClips =
            [
                new CustomModelAnimationClip
                {
                    Id = clipId,
                    FbxObjectId = 2,
                    SourceName = "Idle Take",
                    DisplayName = "idle_loop",
                    FrameRate = new FrameRate(30, 1),
                    StartFrame = 0,
                    FrameCount = 3,
                    RootMotionMode = Dl1RootMotionMode.Recorded,
                    RootBoneName = "root",
                    SourceFingerprint = sourceHash,
                    Included = true,
                },
            ],
            Diagnostics = [],
            BuildSettings = new CustomModelBuildSettings
            {
                CharacterId = "generic_character",
                ResourceName = "GenericModel",
                SurfaceName = "default",
                AnimationScriptAlias = "GenericLibrary",
            },
        };
        document.Validate();
        var package = new CustomModelPackage(
            document,
            source.ToImmutableArray(),
            ImmutableDictionary<string, ImmutableArray<byte>>.Empty);
        var animation = new AnimationClip(
            "Idle Take",
            new FrameRate(30, 1),
            3,
            [
                new TransformTrack(
                    0,
                    [
                        new TransformKeyframe(0, TransformTRS.Identity),
                        new TransformKeyframe(
                            2,
                            new TransformTRS(
                                new Vector3D(0.1, 0.0, 0.0),
                                QuaternionD.Identity,
                                Vector3D.One)),
                    ]),
            ]);
        return new FbxModelAuthoringImportResult(
            package,
            document.CreateRigDefinition(),
            [],
            ImmutableDictionary<Guid, AnimationClip>.Empty.Add(clipId, animation),
            new FbxStrictExportInspection(
                [],
                ImmutableDictionary<string, FbxAnimationStackInspection>.Empty,
                ImmutableDictionary<string, long>.Empty,
                ImmutableDictionary<string, long?>.Empty,
                [],
                0,
                0,
                [],
                [],
                ImmutableDictionary<string, FbxMeshGeometryInspection>.Empty,
                0,
                0,
                [],
                [],
                []));
    }

    private static async Task<Dl1SourceModelBuildResult> WriteSyntheticSourceAsync(
        Dl1SourceModelBuildRequest request,
        CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(request.OutputDirectory);
        string msh = Path.Combine(request.OutputDirectory, $"{request.ResourceName}.msh");
        string chr = Path.Combine(request.OutputDirectory, $"{request.ResourceName}.chr");
        string bscr = Path.Combine(request.OutputDirectory, $"{request.ResourceName}.bscr");
        string ascr = Path.Combine(request.OutputDirectory, $"{request.ResourceName}.ascr");
        string manifest = Path.Combine(request.OutputDirectory, "source-model.json");
        string blocked = Path.Combine(request.OutputDirectory, "blocked-outputs.json");
        await WriteTextAsync(msh, "synthetic msh", cancellationToken);
        await WriteTextAsync(chr, "synthetic chr", cancellationToken);
        await WriteTextAsync(bscr, "synthetic bscr", cancellationToken);
        await WriteTextAsync(
            ascr,
            $"AnimScriptAlias(\"{request.AnimationScriptAlias}.scr\")\n",
            cancellationToken);
        await WriteTextAsync(manifest, "{}", cancellationToken);
        await WriteTextAsync(blocked, "{}", cancellationToken);
        return new Dl1SourceModelBuildResult(
            request.ResourceName,
            msh,
            chr,
            bscr,
            ascr,
            manifest,
            blocked,
            CustomModelBuildState.CompilerReady,
            [],
            [],
            ImmutableDictionary<string, string>.Empty,
            []);
    }

    private static async Task<Dl1OfficialModelCompilerResult> WriteSyntheticModelCompilerAsync(
        Dl1OfficialModelCompilerRequest request,
        CancellationToken cancellationToken)
    {
        string directory = Path.GetDirectoryName(request.OutputRpackPath)!;
        Directory.CreateDirectory(directory);
        string meshObject = Path.Combine(directory, $"{request.ResourceName}.msh_obj");
        string materialDatabase = Path.Combine(directory, "local_dx11.mp");
        string receipt = Path.Combine(directory, "compiler-receipt.json");
        await WriteTextAsync(request.OutputRpackPath, "synthetic rpack", cancellationToken);
        await WriteTextAsync(meshObject, "synthetic mesh object", cancellationToken);
        await WriteTextAsync(materialDatabase, "synthetic material database", cancellationToken);
        await WriteTextAsync(receipt, "{}", cancellationToken);
        string fingerprint = new('a', 64);
        return new Dl1OfficialModelCompilerResult(
            request.ResourceName,
            request.OutputRpackPath,
            meshObject,
            materialDatabase,
            receipt,
            fingerprint,
            [request.ResourceName],
            new CustomModelBuildReceipt
            {
                InputFingerprint = fingerprint,
                ToolFingerprint = fingerprint,
                CompilerFingerprint = fingerprint,
                OutputManifestFingerprint = fingerprint,
                State = CustomModelBuildState.CompilerValidated,
                CompletedUtc = DateTimeOffset.UnixEpoch,
            },
            "Synthetic compiler completed.");
    }

    private static async Task<Dl1OfficialAnimationCompilerResult> WriteSyntheticAnimationsAsync(
        Dl1OfficialAnimationCompilerRequest request,
        CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(request.OutputDirectory);
        var paths = ImmutableDictionary.CreateBuilder<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (PreparedCustomModelAnimation animation in request.Library.Animations)
        {
            string path = Path.Combine(request.OutputDirectory, $"{animation.Name}.anm2_obj");
            await WriteTextAsync(path, $"compiled {animation.Name}", cancellationToken);
            paths.Add(animation.Name, path);
        }

        return new Dl1OfficialAnimationCompilerResult(
            paths.ToImmutable(),
            new string('b', 64),
            "Synthetic animation compiler completed.");
    }

    private static async Task<ImmutableDictionary<string, ImmutableArray<byte>>> SnapshotProjectAsync(
        string projectRoot)
    {
        var snapshot = ImmutableDictionary.CreateBuilder<string, ImmutableArray<byte>>(
            StringComparer.OrdinalIgnoreCase);
        foreach (string path in Directory.EnumerateFiles(projectRoot, "*", SearchOption.AllDirectories)
                     .Order(StringComparer.OrdinalIgnoreCase))
        {
            string relative = Path.GetRelativePath(projectRoot, path).Replace('\\', '/');
            snapshot.Add(relative, (await File.ReadAllBytesAsync(path)).ToImmutableArray());
        }

        return snapshot.ToImmutable();
    }

    private static void AssertProjectSnapshotsEqual(
        ImmutableDictionary<string, ImmutableArray<byte>> expected,
        ImmutableDictionary<string, ImmutableArray<byte>> actual)
    {
        Assert.Equal(expected.Keys.Order(StringComparer.OrdinalIgnoreCase), actual.Keys.Order(StringComparer.OrdinalIgnoreCase));
        foreach ((string path, ImmutableArray<byte> bytes) in expected)
        {
            Assert.True(actual.TryGetValue(path, out ImmutableArray<byte> actualBytes));
            Assert.Equal(bytes.ToArray(), actualBytes.ToArray());
        }
    }

    private static async Task WriteProjectFileAsync(
        string projectRoot,
        string relativePath,
        string contents)
    {
        string path = ResolveProjectFile(projectRoot, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllTextAsync(path, contents);
    }

    private static async Task<string> ReadProjectFileAsync(
        string projectRoot,
        string relativePath) =>
        await File.ReadAllTextAsync(ResolveProjectFile(projectRoot, relativePath));

    private static bool ProjectFileExists(string projectRoot, string relativePath) =>
        File.Exists(ResolveProjectFile(projectRoot, relativePath));

    private static string ResolveProjectFile(string projectRoot, string relativePath) =>
        Path.Combine(projectRoot, relativePath.Replace('/', Path.DirectorySeparatorChar));

    private static async Task WriteTextAsync(
        string path,
        string contents,
        CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllTextAsync(path, contents, cancellationToken);
    }

    private static CustomModelDocument CreateDocument(CustomModelBuildSettings settings)
    {
        byte[] source = "generic custom model"u8.ToArray();
        string sourceHash = Convert.ToHexString(SHA256.HashData(source)).ToLowerInvariant();
        return new CustomModelDocument
        {
            ModelId = new Guid("450bb67e-62cf-5a6f-b3db-4ee1af11bd2d"),
            Name = "Generic custom model",
            RigMode = CustomModelRigMode.StaticProp,
            Source = new CustomModelSourceIdentity
            {
                OriginalFileName = "generic.fbx",
                ContentSha256 = sourceHash,
                FbxVersion = 7400,
            },
            RigSignature = sourceHash,
            Bones = [],
            Meshes = [],
            Materials = [],
            AnimationClips = [],
            Diagnostics = [],
            BuildSettings = settings,
        };
    }
}
