using System.Buffers.Binary;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text.Json;
using ReAnimated.App.Infrastructure;
using ReAnimated.App.ViewModels;
using ReAnimated.Codecs.Fed;
using ReAnimated.Core.Domain;
using ReAnimated.Core.Mathematics;
using ReAnimated.Evaluation;
using ReAnimated.Renderer.D3D11;
using ReAnimated.Retargeting.Ik;
using ReAnimated.Retargeting.Mapping;
using ReAnimated.Tests.Fixtures;
using Vortice.Direct3D;
using Vortice.Direct3D11;
using Vortice.DXGI;
using Vortice.Mathematics;
using Xunit.Abstractions;
using static Vortice.Direct3D11.D3D11;

namespace ReAnimated.Tests;

/// <summary>
/// One inspectable WARP matrix spanning the authoritative animation-authoring
/// stages. Every input is generated by <see cref="RendererAuthoringStageFixture"/>
/// and is safe to redistribute.
/// </summary>
public sealed class RendererAuthoringStageGoldenTests
{
    private const string GoldenFormat =
        "dl-reanimated-renderer-authoring-stage-goldens-v1";
    private const string CaptureFormat =
        "dl-reanimated-renderer-authoring-stage-captures-v1";
    private const int Width = 192;
    private const int Height = 144;
    private const int MaximumGoldenBytes = 128 * 1024;
    private static readonly Vector4 ClearColor =
        new(0.025f, 0.035f, 0.055f, 1.0f);
    private static readonly string[] RequiredStageNames =
    [
        "retarget",
        "root_motion",
        "bone_edit",
        "hand_ik",
        "authored_morph",
        "fed_expression",
        "fpp_projection",
        "helper_overlay",
        "attachment",
    ];
    private static readonly double[] RootTrailFrames =
        [0.0, 0.5, 1.0];
    private static readonly JsonSerializerOptions ArtifactJsonOptions =
        new()
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            WriteIndented = true,
        };

    private readonly ITestOutputHelper _output;

    public RendererAuthoringStageGoldenTests(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    [Trait("Category", "Renderer")]
    [Trait("Gate", "RendererAuthoringGoldens")]
    public void WarpAuthoringStagesMatchRedistributableGoldenMatrix()
    {
        AuthoringMatrix matrix = BuildAuthoringMatrix();
        Assert.Equal(RequiredStageNames, matrix.Stages.Select(
            static stage => stage.Name));

        using var captureSession = new WarpCaptureSession();
        CapturedStage[] captures = matrix.Stages
            .Select(captureSession.Capture)
            .ToArray();
        captureSession.ThrowIfDeviceWasRemoved();

        Assert.Equal(
            captures.Length,
            captures
                .Select(static capture => capture.PixelSha256)
                .Distinct(StringComparer.Ordinal)
                .Count());
        Assert.Equal(
            captures.Length,
            captures
                .Select(static capture => capture.CoverageSha256)
                .Distinct(StringComparer.Ordinal)
                .Count());

        foreach (CapturedStage capture in captures)
        {
            _output.WriteLine(
                string.Create(
                    CultureInfo.InvariantCulture,
                    $"{capture.Name}: pixels={capture.Bounds.PixelCount}, bounds={capture.Bounds.Left},{capture.Bounds.Top}-{capture.Bounds.Right},{capture.Bounds.Bottom}, pixelsSha256={capture.PixelSha256}, coverageSha256={capture.CoverageSha256}"));
        }

        string? outputDirectory =
            Environment.GetEnvironmentVariable(
                "DLR_RENDERER_GOLDEN_OUTPUT");
        if (!string.IsNullOrWhiteSpace(outputDirectory))
        {
            string manifestPath = WriteArtifacts(
                Path.GetFullPath(
                    Environment.ExpandEnvironmentVariables(
                        outputDirectory.Trim())),
                captures);
            _output.WriteLine(
                $"Inspectable renderer captures: {manifestPath}");
        }

        AssertMatchesCommittedGolden(captures);
    }

    private static AuthoringMatrix BuildAuthoringMatrix()
    {
        RigDefinition sourceRig =
            RendererAuthoringStageFixture.CreateSourceRig();
        RigDefinition targetRig =
            RendererAuthoringStageFixture.CreateTargetRig();
        RetargetMap mapping =
            RendererAuthoringStageFixture.CreateMapping(
                sourceRig,
                targetRig);
        AnimationClip bodyClip =
            RendererAuthoringStageFixture.CreateClip(
                sourceRig,
                includeAuthoredMorph: false);
        AnimationClip morphClip =
            RendererAuthoringStageFixture.CreateClip(
                sourceRig,
                includeAuthoredMorph: true);
        BoneEditLayer boneEdit =
            RendererAuthoringStageFixture.CreateBoneEditLayer();
        IkConstraintLayer ik =
            RendererAuthoringStageFixture.CreateIkLayer();
        FedLayerBuildResult fed =
            RendererAuthoringStageFixture.CreateFedLayer(targetRig);
        AttachmentBinding attachment =
            RendererAuthoringStageFixture.CreateAttachmentBinding();
        Dl1AuthoringPolicy rootPolicy =
            Dl1AuthoringPolicy.Create(
                sourceRig,
                targetRig,
                mapping,
                AnimationRootMode.InPlace);
        var evaluator = new AnimationEvaluator();
        double sampleTime = bodyClip.FrameRate.SecondsForFrame(1);

        EvaluationFrame retarget = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            bodyClip,
            sampleTime);
        Assert.True(retarget.Compatibility?.CanEvaluate);
        AssertVectorNear(
            new Vector3D(0.28, 0.08, 0.0),
            retarget.AuthoredPose.GlobalMatrices[
                RendererAuthoringStageFixture.RootBoneIndex].Translation);

        EvaluationFrame root = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            bodyClip,
            sampleTime,
            rootPolicy: rootPolicy);
        AssertVectorNear(
            Vector3D.Zero,
            root.AuthoredPose.GlobalMatrices[
                RendererAuthoringStageFixture.RootBoneIndex].Translation);

        EvaluationFrame edited = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            bodyClip,
            sampleTime,
            rootPolicy,
            editLayers: [boneEdit]);
        Assert.True(
            Math.Abs(
                QuaternionD.Dot(
                    root.AuthoredPose.LocalTransforms[
                        RendererAuthoringStageFixture.UpperArmBoneIndex]
                        .Rotation,
                    edited.AuthoredPose.LocalTransforms[
                        RendererAuthoringStageFixture.UpperArmBoneIndex]
                        .Rotation)) < 0.999);

        EvaluationFrame constrained = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            bodyClip,
            sampleTime,
            rootPolicy,
            [boneEdit],
            ikLayers: [ik]);
        AssertVectorNear(
            RendererAuthoringStageFixture.PostRootPolicyIkTarget,
            constrained.AuthoredPose.GlobalMatrices[
                RendererAuthoringStageFixture.HandBoneIndex].Translation,
            1.0e-6);

        EvaluationFrame morphed = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            morphClip,
            sampleTime,
            rootPolicy,
            [boneEdit],
            [ik]);
        Assert.Equal(
            0.55,
            morphed.AuthoredMorphWeights["smile"],
            8);

        Assert.True(fed.Compatibility.IsComplete);
        Assert.Empty(fed.Diagnostics);
        EvaluationFrame facial = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            morphClip,
            sampleTime,
            rootPolicy,
            [boneEdit],
            [ik],
            morphEditLayers: [fed.Layer]);
        Assert.Equal(
            0.70,
            facial.AuthoredMorphWeights["jaw_drop"],
            6);

        var sceneLens = new CameraLens(
            68.0,
            16.0 / 9.0,
            0.02,
            100.0);
        var handsProjection = new Dl1ProjectionParameters(
            46.0,
            Dl1ProjectionFovAxis.Horizontal,
            16.0 / 9.0,
            0.005,
            Dl1ProjectionFarPlane.Infinite);
        var previewInputs = new Dl1PreviewInputs(
            new Dl1FppProjectionSnapshot(
                sceneLens,
                handsProjection));
        EvaluationFrame fpp = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            morphClip,
            sampleTime,
            rootPolicy,
            [boneEdit],
            [ik],
            [fed.Layer],
            previewProfile: PreviewProfile.FirstPersonAuthoring,
            previewInputs: previewInputs);
        EvaluatedCamera fppCamera =
            Assert.IsType<EvaluatedCamera>(fpp.Camera);
        Assert.Equal(
            EvaluatedCameraSource.Dl1FppEyeCamera,
            fppCamera.Source);
        Assert.Equal(handsProjection, fppCamera.HandsProjection);
        AssertStageApplied(
            fpp,
            Dl1PreviewStageIds.FppSceneProjection);
        AssertStageApplied(
            fpp,
            Dl1PreviewStageIds.FppHandsProjection);

        EvaluationFrame attached = Evaluate(
            evaluator,
            sourceRig,
            targetRig,
            mapping,
            morphClip,
            sampleTime,
            rootPolicy,
            [boneEdit],
            [ik],
            [fed.Layer],
            attachments: [attachment]);
        Assert.Single(attached.DisplayAttachments);

        MeshRenderData actor =
            RendererAuthoringStageFixture.CreateActorMesh(targetRig);
        RenderFrameSnapshot retargetFrame =
            CreateOrbitFrame(retarget, actor);
        RenderFrameSnapshot rootFrame =
            CreateOrbitFrame(root, actor) with
            {
                AuthoringOverlays =
                    new RenderAuthoringOverlayState(
                        new RenderAuthoringOverlayOptions(
                            ShowRootMotionTrail: true),
                        new RootMotionTrailRenderData(
                            SampleRawRootTrail(
                                evaluator,
                                sourceRig,
                                targetRig,
                                mapping,
                                bodyClip),
                            currentSampleIndex: 2)),
            };
        RenderFrameSnapshot editFrame =
            CreateOrbitFrame(edited, actor);
        RenderFrameSnapshot ikFrame =
            CreateOrbitFrame(constrained, actor);
        RenderFrameSnapshot morphFrame =
            CreateOrbitFrame(morphed, actor);
        RenderFrameSnapshot facialFrame =
            CreateOrbitFrame(facial, actor);

        RenderProjectionParameters renderHandsProjection =
            Dl1PreviewCameraAdapter.ToRenderProjection(
                fppCamera.HandsProjection ??
                throw new InvalidOperationException(
                    "The evaluated FPP camera lost its captured hands projection."));
        RenderFrameSnapshot fppFrame = CreateFrame(
            fpp,
            [
                actor,
                RendererAuthoringStageFixture.CreateFppHandsMesh(),
            ],
            Dl1PreviewCameraAdapter.ToRenderCamera(
                fppCamera,
                preserveLensAspectRatio: true)) with
        {
            FppProjectionState = new RenderFppProjectionState(
                RouteHandsMeshes: true,
                SceneAspectRatio:
                    checked((float)fppCamera.Lens.AspectRatio),
                HandsProjection: renderHandsProjection),
        };

        SkeletonRenderData helperSkeleton =
            CorePreviewAdapter.ToRenderSkeleton(
                facial.DisplayPose,
                RendererAuthoringStageFixture.HelperBoneIndex) with
            {
                ShowDeformBones = false,
                ShowHelpers = true,
                ShowCameraHelpers = false,
                ShowProps = true,
            };
        Assert.Equal(
            3,
            helperSkeleton.Bones.Count(helperSkeleton.IsVisible));
        RenderFrameSnapshot helperFrame =
            CreateOrbitFrame(facial, actor) with
            {
                Skeleton = helperSkeleton,
                AuthoringOverlays =
                    new RenderAuthoringOverlayState(
                        new RenderAuthoringOverlayOptions(
                            ShowBoneLocalAxes: true),
                        null),
            };

        AttachmentRenderAsset attachmentAsset =
            RendererAuthoringStageFixture.CreateAttachmentAsset();
        AttachmentSceneComposition attachmentScene =
            AttachmentSceneComposer.Compose(
                [actor],
                attached.DisplayAttachments,
                new Dictionary<Guid, AttachmentRenderAsset>
                {
                    [attachmentAsset.ProjectAssetId] = attachmentAsset,
                });
        Assert.Empty(attachmentScene.Diagnostics);
        Assert.Equal(2, attachmentScene.Meshes.Length);
        RenderFrameSnapshot attachmentFrame =
            CreateFrame(
                attached,
                attachmentScene.Meshes,
                RendererAuthoringStageFixture.OrbitCamera);

        return new AuthoringMatrix(
        [
            new StageScene("retarget", retargetFrame),
            new StageScene(
                "root_motion",
                rootFrame,
                RenderAuthoringOverlay: true),
            new StageScene("bone_edit", editFrame),
            new StageScene("hand_ik", ikFrame),
            new StageScene("authored_morph", morphFrame),
            new StageScene("fed_expression", facialFrame),
            new StageScene(
                "fpp_projection",
                fppFrame,
                RenderFppSafeFrame: true,
                VerifyCpuGpuBounds: false),
            new StageScene(
                "helper_overlay",
                helperFrame,
                RenderSkeleton: true,
                RenderAuthoringOverlay: true),
            new StageScene("attachment", attachmentFrame),
        ]);
    }

    private static EvaluationFrame Evaluate(
        AnimationEvaluator evaluator,
        RigDefinition sourceRig,
        RigDefinition targetRig,
        RetargetMap mapping,
        AnimationClip clip,
        double timeSeconds,
        Dl1AuthoringPolicy? rootPolicy = null,
        IEnumerable<BoneEditLayer>? editLayers = null,
        IEnumerable<IkConstraintLayer>? ikLayers = null,
        IEnumerable<MorphEditLayer>? morphEditLayers = null,
        PreviewProfile? previewProfile = null,
        Dl1PreviewInputs? previewInputs = null,
        IEnumerable<AttachmentBinding>? attachments = null) =>
        evaluator.Evaluate(
            new EvaluationRequest(
                sourceRig,
                targetRig,
                clip,
                timeSeconds,
                previewProfile ?? PreviewProfile.RawAuthoring,
                mapping,
                editLayers,
                purpose: EvaluationPurpose.Preview,
                attachments: attachments,
                dl1AuthoringPolicy: rootPolicy,
                morphEditLayers: morphEditLayers,
                ikLayers: ikLayers,
                dl1PreviewInputs: previewInputs));

    private static RenderFrameSnapshot CreateOrbitFrame(
        EvaluationFrame evaluation,
        MeshRenderData actor) =>
        CreateFrame(
            evaluation,
            [actor],
            RendererAuthoringStageFixture.OrbitCamera);

    private static RenderFrameSnapshot CreateFrame(
        EvaluationFrame evaluation,
        IReadOnlyList<MeshRenderData> meshes,
        RenderCamera camera) =>
        new(
            ClearColor,
            camera,
            meshes,
            CorePreviewAdapter.ToRenderSkeleton(
                evaluation.DisplayPose),
            [],
            ToMorphWeights(evaluation.DisplayMorphWeights));

    private static MorphWeight[] ToMorphWeights(
        IReadOnlyDictionary<string, double> weights) =>
        weights
            .OrderBy(static pair => pair.Key, StringComparer.Ordinal)
            .Select(static pair =>
                new MorphWeight(
                    pair.Key,
                    checked((float)pair.Value)))
            .ToArray();

    private static Vector3[] SampleRawRootTrail(
        AnimationEvaluator evaluator,
        RigDefinition sourceRig,
        RigDefinition targetRig,
        RetargetMap mapping,
        AnimationClip bodyClip) =>
        RootTrailFrames
            .Select(frame =>
                Evaluate(
                    evaluator,
                    sourceRig,
                    targetRig,
                    mapping,
                    bodyClip,
                    bodyClip.FrameRate.SecondsForFrame(frame))
                .DisplayPose.GlobalMatrices[
                    RendererAuthoringStageFixture.RootBoneIndex]
                .Translation)
            .Select(ToVector3)
            .ToArray();

    private static void AssertStageApplied(
        EvaluationFrame frame,
        string stageId)
    {
        Dl1PreviewStageReport stage = Assert.Single(
            frame.Dl1PreviewStages,
            candidate => candidate.StageId == stageId);
        Assert.Equal(Dl1PreviewStageStatus.Applied, stage.Status);
    }

    private static void AssertVectorNear(
        Vector3D expected,
        Vector3D actual,
        double tolerance = 1.0e-8)
    {
        Assert.InRange(
            Vector3D.Distance(expected, actual),
            0.0,
            tolerance);
    }

    private static Vector3 ToVector3(Vector3D value) =>
        new(
            checked((float)value.X),
            checked((float)value.Y),
            checked((float)value.Z));

    private static void AssertMatchesCommittedGolden(
        IReadOnlyList<CapturedStage> captures)
    {
        string path = Path.Combine(
            FindRepositoryRoot(),
            "tests",
            "fixtures",
            "renderer_authoring_stage_goldens_v1.json");
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                "The committed renderer authoring-stage golden is missing. " +
                "A capture output is diagnostic evidence and must not silently bless a new golden.",
                path);
        }

        byte[] bytes = File.ReadAllBytes(path);
        if (bytes.Length is <= 0 or > MaximumGoldenBytes)
        {
            throw new InvalidDataException(
                $"Renderer golden length {bytes.Length:N0} is outside the bounded 1-{MaximumGoldenBytes:N0} byte range.");
        }

        using JsonDocument document = JsonDocument.Parse(bytes);
        JsonElement root = document.RootElement;
        Assert.Equal(
            GoldenFormat,
            RequiredString(root, "format"));
        Assert.Equal(Width, RequiredInt32(root, "width"));
        Assert.Equal(Height, RequiredInt32(root, "height"));
        JsonElement stages = RequiredProperty(root, "stages");
        Assert.Equal(JsonValueKind.Array, stages.ValueKind);
        JsonElement[] expectedStages =
            stages.EnumerateArray().ToArray();
        Assert.Equal(RequiredStageNames.Length, expectedStages.Length);
        Assert.Equal(captures.Count, expectedStages.Length);
        Assert.Equal(
            RequiredStageNames,
            expectedStages.Select(
                static stage => RequiredString(stage, "name")));

        for (int index = 0; index < captures.Count; index++)
        {
            CapturedStage actual = captures[index];
            JsonElement expected = expectedStages[index];
            Assert.Equal(
                RequiredString(expected, "pixelSha256"),
                actual.PixelSha256);
            Assert.Equal(
                RequiredString(expected, "coverageSha256"),
                actual.CoverageSha256);
            Assert.Equal(
                RequiredInt32(expected, "pixelCount"),
                actual.Bounds.PixelCount);
            Assert.Equal(
                RequiredInt32(expected, "left"),
                actual.Bounds.Left);
            Assert.Equal(
                RequiredInt32(expected, "top"),
                actual.Bounds.Top);
            Assert.Equal(
                RequiredInt32(expected, "right"),
                actual.Bounds.Right);
            Assert.Equal(
                RequiredInt32(expected, "bottom"),
                actual.Bounds.Bottom);
        }
    }

    private static string WriteArtifacts(
        string outputDirectory,
        IReadOnlyList<CapturedStage> captures)
    {
        Directory.CreateDirectory(outputDirectory);
        var stages = new List<object>(captures.Count);
        foreach (CapturedStage capture in captures)
        {
            string fileName = $"{capture.Name}.bmp";
            byte[] bitmap = BuildTopDownBgraBitmap(capture.Pixels);
            WriteAtomic(
                Path.Combine(outputDirectory, fileName),
                bitmap);
            stages.Add(
                new
                {
                    capture.Name,
                    File = fileName,
                    BmpSha256 = ComputeSha256(bitmap),
                    capture.PixelSha256,
                    capture.CoverageSha256,
                    capture.Bounds.PixelCount,
                    capture.Bounds.Left,
                    capture.Bounds.Top,
                    capture.Bounds.Right,
                    capture.Bounds.Bottom,
                });
        }

        byte[] manifest = JsonSerializer.SerializeToUtf8Bytes(
            new
            {
                Format = CaptureFormat,
                GoldenFormat,
                Width,
                Height,
                Stages = stages,
            },
            ArtifactJsonOptions);
        string manifestPath =
            Path.Combine(outputDirectory, "manifest.json");
        WriteAtomic(manifestPath, manifest);
        return manifestPath;
    }

    private static byte[] BuildTopDownBgraBitmap(byte[] pixels)
    {
        int pixelBytes = checked(Width * Height * 4);
        if (pixels.Length != pixelBytes)
        {
            throw new InvalidDataException(
                $"Capture contains {pixels.Length:N0} bytes; expected {pixelBytes:N0}.");
        }

        const int headerBytes = 14 + 40;
        byte[] bitmap = new byte[checked(headerBytes + pixelBytes)];
        bitmap[0] = (byte)'B';
        bitmap[1] = (byte)'M';
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(2, 4),
            bitmap.Length);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(10, 4),
            headerBytes);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(14, 4),
            40);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(18, 4),
            Width);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(22, 4),
            -Height);
        BinaryPrimitives.WriteInt16LittleEndian(
            bitmap.AsSpan(26, 2),
            1);
        BinaryPrimitives.WriteInt16LittleEndian(
            bitmap.AsSpan(28, 2),
            32);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(34, 4),
            pixelBytes);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(38, 4),
            2_835);
        BinaryPrimitives.WriteInt32LittleEndian(
            bitmap.AsSpan(42, 4),
            2_835);
        pixels.CopyTo(bitmap, headerBytes);
        return bitmap;
    }

    private static void WriteAtomic(string path, byte[] bytes)
    {
        string temporaryPath =
            path + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllBytes(temporaryPath, bytes);
            File.Move(temporaryPath, path, overwrite: true);
        }
        finally
        {
            if (File.Exists(temporaryPath))
            {
                File.Delete(temporaryPath);
            }
        }
    }

    private static string FindRepositoryRoot()
    {
        string[] starts =
        [
            Directory.GetCurrentDirectory(),
            AppContext.BaseDirectory,
        ];
        foreach (string start in starts)
        {
            DirectoryInfo? current =
                new DirectoryInfo(Path.GetFullPath(start));
            while (current is not null)
            {
                if (File.Exists(
                        Path.Combine(
                            current.FullName,
                            "DLReAnimated.slnx")))
                {
                    return current.FullName;
                }

                current = current.Parent;
            }
        }

        throw new DirectoryNotFoundException(
            "Could not locate the DL ReAnimated repository root.");
    }

    private static JsonElement RequiredProperty(
        JsonElement element,
        string name) =>
        element.TryGetProperty(name, out JsonElement value)
            ? value
            : throw new InvalidDataException(
                $"Renderer golden is missing '{name}'.");

    private static string RequiredString(
        JsonElement element,
        string name) =>
        RequiredProperty(element, name).GetString() ??
        throw new InvalidDataException(
            $"Renderer golden '{name}' is null.");

    private static int RequiredInt32(
        JsonElement element,
        string name) =>
        RequiredProperty(element, name).GetInt32();

    private static string ComputeSha256(ReadOnlySpan<byte> bytes) =>
        Convert.ToHexString(SHA256.HashData(bytes))
            .ToLowerInvariant();

    private sealed record AuthoringMatrix(
        IReadOnlyList<StageScene> Stages);

    private sealed record StageScene(
        string Name,
        RenderFrameSnapshot Frame,
        bool RenderSkeleton = false,
        bool RenderAuthoringOverlay = false,
        bool RenderFppSafeFrame = false,
        bool VerifyCpuGpuBounds = true);

    private sealed record CapturedStage(
        string Name,
        byte[] Pixels,
        PixelBounds Bounds,
        string PixelSha256,
        string CoverageSha256);

    private readonly record struct PixelBounds(
        int Left,
        int Top,
        int Right,
        int Bottom,
        int PixelCount);

    private sealed class WarpCaptureSession : IDisposable
    {
        private readonly ID3D11Device _device;
        private readonly ID3D11DeviceContext _context;
        private readonly ID3D11Texture2D _color;
        private readonly ID3D11RenderTargetView _renderTarget;
        private readonly ID3D11Texture2D _depth;
        private readonly ID3D11DepthStencilView _depthStencil;
        private readonly ID3D11Texture2D _staging;
        private readonly GpuSkinnedMeshRenderPass _meshPass = new();
        private readonly SkeletonRenderPass _skeletonPass = new();
        private readonly AuthoringOverlayRenderPass _authoringPass = new();
        private readonly FppSafeFrameRenderPass _fppSafeFramePass = new();
        private long _frameNumber;
        private bool _disposed;

        public WarpCaptureSession()
        {
            D3D11CreateDevice(
                null,
                DriverType.Warp,
                DeviceCreationFlags.BgraSupport,
                [FeatureLevel.Level_11_0],
                out ID3D11Device? device,
                out _,
                out ID3D11DeviceContext? context).CheckError();
            _device = device ??
                throw new InvalidOperationException(
                    "WARP returned no D3D11 device.");
            _context = context ??
                throw new InvalidOperationException(
                    "WARP returned no immediate context.");
            _color = _device.CreateTexture2D(
                CreateTextureDescription(
                    Format.B8G8R8A8_UNorm,
                    ResourceUsage.Default,
                    BindFlags.RenderTarget,
                    CpuAccessFlags.None));
            _renderTarget = _device.CreateRenderTargetView(_color);
            _depth = _device.CreateTexture2D(
                CreateTextureDescription(
                    Format.D24_UNorm_S8_UInt,
                    ResourceUsage.Default,
                    BindFlags.DepthStencil,
                    CpuAccessFlags.None));
            _depthStencil =
                _device.CreateDepthStencilView(_depth);
            _staging = _device.CreateTexture2D(
                CreateTextureDescription(
                    Format.B8G8R8A8_UNorm,
                    ResourceUsage.Staging,
                    BindFlags.None,
                    CpuAccessFlags.Read));
        }

        public CapturedStage Capture(StageScene stage)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            ArgumentNullException.ThrowIfNull(stage);
            if (stage.Frame.ClearColor != ClearColor)
            {
                throw new InvalidDataException(
                    $"Stage '{stage.Name}' changed the matrix clear color.");
            }

            _context.OMSetRenderTargets(
                _renderTarget,
                _depthStencil);
            _context.RSSetViewport(0, 0, Width, Height);
            ClearTargets(stage.Frame.ClearColor);
            byte[] clearPixels = ReadBack();

            var diagnostics = new List<string>();
            var renderContext = new D3D11RenderFrameContext(
                _device,
                _context,
                _renderTarget,
                _depthStencil,
                Width,
                Height,
                ++_frameNumber,
                diagnostics.Add);
            _meshPass.Render(in renderContext, stage.Frame);
            _context.Flush();
            byte[] meshPixels = ReadBack();
            if (stage.VerifyCpuGpuBounds)
            {
                AssertCpuGpuBounds(stage, clearPixels, meshPixels);
            }

            if (stage.RenderSkeleton)
            {
                _skeletonPass.Render(in renderContext, stage.Frame);
            }

            if (stage.RenderAuthoringOverlay)
            {
                _authoringPass.Render(in renderContext, stage.Frame);
            }

            if (stage.RenderFppSafeFrame)
            {
                _fppSafeFramePass.Render(in renderContext, stage.Frame);
            }

            _context.Flush();
            if (diagnostics.Count > 0)
            {
                throw new InvalidOperationException(
                    $"Stage '{stage.Name}' produced renderer diagnostics: " +
                    string.Join(" | ", diagnostics));
            }

            byte[] pixels = ReadBack();
            (PixelBounds bounds, byte[] coverageMask) =
                MeasureCoverage(clearPixels, pixels);
            if (bounds.PixelCount <= 0)
            {
                throw new InvalidOperationException(
                    $"Stage '{stage.Name}' rendered no changed pixels.");
            }

            return new CapturedStage(
                stage.Name,
                pixels,
                bounds,
                ComputeSha256(pixels),
                ComputeSha256(coverageMask));
        }

        public void ThrowIfDeviceWasRemoved()
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            _device.DeviceRemovedReason.CheckError();
        }

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            _fppSafeFramePass.Dispose();
            _authoringPass.Dispose();
            _skeletonPass.Dispose();
            _meshPass.Dispose();
            _staging.Dispose();
            _depthStencil.Dispose();
            _depth.Dispose();
            _renderTarget.Dispose();
            _color.Dispose();
            _context.Dispose();
            _device.Dispose();
        }

        private static void AssertCpuGpuBounds(
            StageScene stage,
            byte[] clearPixels,
            byte[] meshPixels)
        {
            PixelBounds gpu =
                MeasureCoverage(clearPixels, meshPixels).Bounds;
            PixelBounds cpu = MeasureCpuProjectedBounds(
                stage.Frame);
            Assert.True(
                gpu.PixelCount > 0,
                $"Stage '{stage.Name}' produced no mesh pixels before overlays.");
            Assert.InRange(Math.Abs(gpu.Left - cpu.Left), 0, 3);
            Assert.InRange(Math.Abs(gpu.Top - cpu.Top), 0, 3);
            Assert.InRange(Math.Abs(gpu.Right - cpu.Right), 0, 3);
            Assert.InRange(Math.Abs(gpu.Bottom - cpu.Bottom), 0, 3);
        }

        private static PixelBounds MeasureCpuProjectedBounds(
            RenderFrameSnapshot frame)
        {
            var projected = new List<Vector2>();
            Matrix4x4 viewProjection =
                RenderCameraMath.CreateViewProjection(
                    frame.Camera,
                    Width,
                    Height);
            foreach (MeshRenderData mesh in frame.Meshes)
            {
                CpuDeformedVertex[] vertices =
                    CpuMeshDeformationEvaluator.Evaluate(
                        mesh,
                        mesh.IsSkinned
                            ? frame.Skeleton
                            : null,
                        frame.MorphWeights);
                projected.AddRange(
                    vertices.Select(vertex =>
                        Project(vertex.Position, viewProjection)));
            }

            if (projected.Count == 0)
            {
                throw new InvalidDataException(
                    "A CPU/GPU bounds stage has no projected vertices.");
            }

            return new PixelBounds(
                checked((int)MathF.Floor(
                    projected.Min(static point => point.X))),
                checked((int)MathF.Floor(
                    projected.Min(static point => point.Y))),
                checked((int)MathF.Ceiling(
                    projected.Max(static point => point.X))),
                checked((int)MathF.Ceiling(
                    projected.Max(static point => point.Y))),
                0);
        }

        private static Vector2 Project(
            Vector3 position,
            Matrix4x4 viewProjection)
        {
            Vector4 clip = Vector4.Transform(
                new Vector4(position, 1.0f),
                viewProjection);
            if (!float.IsFinite(clip.X) ||
                !float.IsFinite(clip.Y) ||
                !float.IsFinite(clip.W) ||
                MathF.Abs(clip.W) <= 1.0e-8f)
            {
                throw new InvalidDataException(
                    "The CPU reference produced a non-projectable vertex.");
            }

            Vector2 normalized =
                new(clip.X / clip.W, clip.Y / clip.W);
            return new Vector2(
                (normalized.X * 0.5f + 0.5f) * Width,
                (-normalized.Y * 0.5f + 0.5f) * Height);
        }

        private static (
            PixelBounds Bounds,
            byte[] CoverageMask) MeasureCoverage(
                byte[] clearPixels,
                byte[] pixels)
        {
            if (clearPixels.Length != pixels.Length ||
                pixels.Length != Width * Height * 4)
            {
                throw new InvalidDataException(
                    "Renderer readback dimensions changed during capture.");
            }

            int left = Width;
            int top = Height;
            int right = -1;
            int bottom = -1;
            int count = 0;
            byte[] mask =
                new byte[(Width * Height + 7) / 8];
            for (int pixelIndex = 0;
                 pixelIndex < Width * Height;
                 pixelIndex++)
            {
                int byteIndex = pixelIndex * 4;
                bool changed =
                    pixels[byteIndex] != clearPixels[byteIndex] ||
                    pixels[byteIndex + 1] !=
                        clearPixels[byteIndex + 1] ||
                    pixels[byteIndex + 2] !=
                        clearPixels[byteIndex + 2];
                if (!changed)
                {
                    continue;
                }

                mask[pixelIndex >> 3] |=
                    checked((byte)(1 << (pixelIndex & 7)));
                int x = pixelIndex % Width;
                int y = pixelIndex / Width;
                left = Math.Min(left, x);
                top = Math.Min(top, y);
                right = Math.Max(right, x);
                bottom = Math.Max(bottom, y);
                count++;
            }

            return (
                new PixelBounds(
                    left,
                    top,
                    right,
                    bottom,
                    count),
                mask);
        }

        private void ClearTargets(Vector4 clearColor)
        {
            _context.ClearRenderTargetView(
                _renderTarget,
                new Color4(
                    clearColor.X,
                    clearColor.Y,
                    clearColor.Z,
                    clearColor.W));
            _context.ClearDepthStencilView(
                _depthStencil,
                DepthStencilClearFlags.Depth,
                1.0f,
                0);
        }

        private byte[] ReadBack()
        {
            _context.CopyResource(_staging, _color);
            _context.Flush();
            _context.Map(
                _staging,
                0,
                MapMode.Read,
                Vortice.Direct3D11.MapFlags.None,
                out MappedSubresource mapped).CheckError();
            try
            {
                byte[] pixels =
                    new byte[Width * Height * 4];
                int rowBytes = Width * 4;
                for (int row = 0; row < Height; row++)
                {
                    Marshal.Copy(
                        IntPtr.Add(
                            mapped.DataPointer,
                            checked((int)(row * mapped.RowPitch))),
                        pixels,
                        row * rowBytes,
                        rowBytes);
                }

                return pixels;
            }
            finally
            {
                _context.Unmap(_staging, 0);
            }
        }

        private static Texture2DDescription CreateTextureDescription(
            Format format,
            ResourceUsage usage,
            BindFlags bindFlags,
            CpuAccessFlags cpuAccessFlags) =>
            new()
            {
                Width = Width,
                Height = Height,
                MipLevels = 1,
                ArraySize = 1,
                Format = format,
                SampleDescription = new SampleDescription(1, 0),
                Usage = usage,
                BindFlags = bindFlags,
                CPUAccessFlags = cpuAccessFlags,
                MiscFlags = ResourceOptionFlags.None,
            };
    }
}
